services:
  customer-service:
    image: leetuan0342/my-spring-app:1.0
    container_name: customer-service
    ports:
      - "8081:8081"
    networks:
      - customer-network

networks:
  customer-network:
    external: true
