spring:
    config:
        import: optional:file:.env.properties
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        format_sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect    

